#!bin/bash 
#start install required packages 
echo "start installing required packages" 
yum -y install gcc*
yum -y install binutils-* 
yum -y install compat-libstdc++-* 
yum -y install compat-libstdc++-*
yum -y install elfutils-libelf-*
yum -y install elfutils-libelf-devel-* 
yum -y install gcc-* 
yum -y install gcc-c++-* 
yum -y install glibc-* 
yum -y install glibc-* 
yum -y install glibc-common-* 
yum -y install glibc-devel-* 
yum -y install glibc-devel-* 
yum -y install glibc-headers-* 
yum -y install ksh-* 
yum -y install libaio-* 
yum -y install libaio-* 
yum -y install libaio-devel-* 
yum -y install libaio-devel-* 
yum -y install libgcc-* 
yum -y install libgcc-* 
yum -y install libstdc++-* 
yum -y install libstdc++-* 
yum -y install libstdc++-devel* 
yum -y install make-* 
yum -y install sysstat-* 
yum -y install unixODBC-* 
